#!/bin/bash
../2014PileupWorkshop/scripts/mkcxx.pl -f -s -1 -i '-I../2014PileupWorkshop/Framework -Wno-deprecated-declarations' -l '-L../2014PileupWorkshop/Framework -lEventMixer -lz -lfastjetcontribfragile -lgsl -lgslcblas -lm'
